# Generated by Django 4.2.3 on 2023-07-30 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='type',
        ),
    ]
